[libraries]
kafka-bom = { group = "com.bakdata.kafka", name = "kafka-bom", version = "1.2.1" }
kafka-streams-avro-serde = { group = "io.confluent", name = "kafka-streams-avro-serde" }
kafka-connect-runtime = { group = "org.apache.kafka", name = "connect-runtime" }
largeMessage-bom = { group = "com.bakdata.kafka", name = "large-message-bom", version = "3.1.0" }
largeMessage-serde = { group = "com.bakdata.kafka", name = "large-message-serde" }
errorHandling-bom = { group = "com.bakdata.kafka", name = "error-handling-bom", version = "2.0.0" }
errorHandling-avro = { group = "com.bakdata.kafka", name = "error-handling-avro" }
streamsBootstrap-bom = { group = "com.bakdata.kafka", name = "streams-bootstrap-bom", version = "5.1.2" }
streamsBootstrap-largeMessage = { group = "com.bakdata.kafka", name = "streams-bootstrap-large-messages" }
streamsBootstrap-cli = { group = "com.bakdata.kafka", name = "streams-bootstrap-cli" }
bruteForce-serde = { group = "com.bakdata.kafka", name = "brute-force-serde", version = "1.4.0" }
jool = { group = "org.jooq", name = "jool", version = "0.9.15" }
log4j-slf4j2 = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version = "2.25.1" }

junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "5.13.4" }
assertj = { group = "org.assertj", name = "assertj-core", version = "3.27.6" }
streamsBootstrap-test = { group = "com.bakdata.kafka", name = "streams-bootstrap-test" }

[plugins]
release = { id = "com.bakdata.release", version = "1.11.1" }
sonar = { id = "com.bakdata.sonar", version = "1.11.1" }
sonatype = { id = "com.bakdata.sonatype", version = "1.11.1" }
lombok = { id = "io.freefair.lombok", version = "8.14.2" }
jib = { id = "com.bakdata.jib", version = "1.11.1" }
avro = { id = "com.bakdata.avro", version = "1.5.0" }
